Repository murgatt/recode-converter, pull requests merged in 2020-08, with the labels that each got.

#51 feat: remove useless start screen
  src/i18n/en.json
  src/i18n/fr.json
  src/routes/HomePage.js
  src/routes/index.js
Labels: enhancement

#52 fix(conversion): wrong status if file added during conversion
  src/store/conversion/conversion.actions.js
  src/store/conversion/conversion.reducer.js
  src/store/conversion/conversion.selectors.js
  src/store/file/file.actions.js
  src/store/file/file.selectors.js
Labels: bug

#53 feat: check for available update on start
  public/electron.js
  src/App.js
  src/components/VersionAlert/VersionAlert.js
  src/components/VersionAlert/index.js
  src/constants.js
  src/i18n/en.json
  src/i18n/fr.json
  src/registerElectronEvents.js
  src/store/ui/ui.actions.js
  src/store/ui/ui.reducer.js
  src/store/ui/ui.selectors.js
  src/utils.js
Labels: enhancement

#54 build(dependencies): move testing library to dev dependencies
  package.json
Labels: dependencies
